import pyautogui
import time
time.sleep(3.0)
pyautogui.hotkey('win','r')
time.sleep(0.5)
pyautogui.typewrite("temp", interval=0.02)
time.sleep(0.5)
pyautogui.hotkey('enter')
time.sleep(5)
pyautogui.hotkey('ctrl','a')
time.sleep(2.0)
pyautogui.hotkey('shift','delete')
time.sleep(1.0)
pyautogui.hotkey('enter')
time.sleep(3.0)
pyautogui.hotkey('enter')
time.sleep(5.0)
pyautogui.press('up')
time.sleep(1.0)
pyautogui.hotkey('enter')
time.sleep(1.0)
pyautogui.press('down')
time.sleep(1.0)
pyautogui.hotkey('enter')
time.sleep(3.0)
pyautogui.press('up')
time.sleep(1.0)
pyautogui.press('right')
time.sleep(1.0)
pyautogui.hotkey('enter')
time.sleep(2.0)
pyautogui.hotkey('ALT','f4')